### ISSUE TITLE
点击下一步的时候，除了菊花在转，就没反应

### ISSUE THREAD

**Issue by ali0201** [xiaofeixia9/VideoClip#1]
iOS10，iPhone 6

**Comment by alexlee928** [comment]
有同样的错误

**Comment by xiaofeixia9** [comment]
我这个是项目中一个裁剪视频demo，看一下FMLClipVideoViewController这个类的346行，裁剪后的url传递给下一个视频滤镜控制器，这个控制器是我同事做的，我就不分享了。你可以自己在得到被裁剪后的url做一些操作。
